# Generated by Django 3.1.2 on 2020-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('propietario', models.CharField(max_length=80, verbose_name='Propietario')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('numero_telefono', models.CharField(max_length=100, verbose_name='Numero_telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'vivero',
                'verbose_name_plural': 'viveros',
            },
        ),
        migrations.AlterModelOptions(
            name='plantas',
            options={'verbose_name': 'Planta', 'verbose_name_plural': 'plantas'},
        ),
    ]
