# Generated by Django 3.1.2 on 2020-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_auto_20201113_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivero',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Direccion'),
        ),
    ]
