# Generated by Django 3.1.2 on 2020-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0003_auto_20201113_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
    ]
